# Generated by Django 6.1.1 on 2026-09-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=64, unique=True)),
                ('display_alias', models.CharField(blank=True, max_length=64)),
                ('brand', models.CharField(blank=True, default='Unknown Brand', max_length=128)),
                ('category_cluster_id', models.CharField(max_length=64)),
                ('category_code', models.CharField(blank=True, max_length=128, null=True)),
                ('category_label', models.CharField(blank=True, max_length=128, null=True)),
                ('category_label_verified', models.BooleanField(default=False)),
                ('representative_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observed_launch_date', models.DateField()),
                ('eligibility', models.CharField(choices=[('eligible', 'eligible'), ('insufficient_history', 'insufficient_history'), ('insufficient_future_window', 'insufficient_future_window')], default='eligible', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initial', 'initial'), ('adaptive', 'adaptive')], max_length=16)),
                ('day_cutoff_used', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('forecast_7d', models.FloatField()),
                ('forecast_14d', models.FloatField()),
                ('range_low_7d', models.FloatField(blank=True, null=True)),
                ('range_high_7d', models.FloatField(blank=True, null=True)),
                ('range_low_14d', models.FloatField(blank=True, null=True)),
                ('range_high_14d', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecast.product')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_cutoff_used', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status_code', models.CharField(choices=[('ABOVE_EXPECTATION', 'ABOVE_EXPECTATION'), ('ON_TRACK', 'ON_TRACK'), ('HIGH_INTEREST_LOW_CONVERSION', 'HIGH_INTEREST_LOW_CONVERSION'), ('BELOW_EXPECTATION', 'BELOW_EXPECTATION')], max_length=32)),
                ('retailer_action', models.CharField(choices=[('REPLENISH', 'REPLENISH'), ('MAINTAIN', 'MAINTAIN'), ('REVIEW_CAMPAIGN', 'REVIEW_CAMPAIGN'), ('HOLD', 'HOLD')], max_length=32)),
                ('manufacturer_action', models.CharField(choices=[('SCALE_PRODUCTION', 'SCALE_PRODUCTION'), ('MAINTAIN_PRODUCTION', 'MAINTAIN_PRODUCTION'), ('WAIT_FOR_CONFIRMATION', 'WAIT_FOR_CONFIRMATION'), ('REDUCE_NEXT_BATCH', 'REDUCE_NEXT_BATCH')], max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='forecast.product')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'approve'), ('modify', 'modify'), ('reject', 'reject')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('modified_payload', models.JSONField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='forecast.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_inventory', models.FloatField()),
                ('reorder_lead_time_days', models.PositiveIntegerField()),
                ('safety_stock_days', models.PositiveIntegerField(blank=True, null=True)),
                ('production_capacity', models.FloatField()),
                ('campaign_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unknown', 'Unknown')], default='Unknown', max_length=16)),
                ('event_to_unit_ratio', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_input', to='forecast.product')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_cutoff', models.PositiveSmallIntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('cart_events', models.PositiveIntegerField(default=0)),
                ('unique_cart_users', models.PositiveIntegerField(default=0)),
                ('remove_events', models.PositiveIntegerField(default=0)),
                ('purchase_events', models.PositiveIntegerField(default=0)),
                ('unique_purchasers', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_metrics', to='forecast.product')),
            ],
            options={
                'ordering': ['day_cutoff'],
                'unique_together': {('product', 'day_cutoff')},
            },
        ),
        migrations.CreateModel(
            name='AnalogLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_rank', models.PositiveSmallIntegerField()),
                ('similarity_score', models.FloatField()),
                ('similarity_reason', models.CharField(max_length=128)),
                ('analog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forecast.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='forecast.product')),
            ],
            options={
                'ordering': ['similarity_rank'],
                'unique_together': {('target_product', 'similarity_rank')},
            },
        ),
    ]
