# Generated by Django 6.1.1 on 2026-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analoglink',
            name='similarity_reason',
        ),
        migrations.AddField(
            model_name='analoglink',
            name='actual_purchase_events_14d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analoglink',
            name='actual_purchase_events_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analoglink',
            name='similarity_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='change_percent_14d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='change_percent_7d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
